CREATE SCHEMA CONTROLCINE;

CREATE TABLE CONTROLCINE.CINEMA(
	CNPJ CHAR(14) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	FRANQUIA VARCHAR(255)
);
CREATE TABLE CONTROLCINE.SALA(
	ID SERIAL PRIMARY KEY,
	CAPACIDADE INT NOT NULL,
	CNPJ CHAR(14) NOT NULL,
	CONSTRAINT fk_sala_cinema FOREIGN KEY (CNPJ) REFERENCES CONTROLCINE.CINEMA(CNPJ)
);


CREATE TABLE CONTROLCINE.FILME(
	ID SERIAL PRIMARY KEY,
	TITULO VARCHAR(255) NOT NULL,
	DURACAO TIME NOT NULL,
	CAPA BYTEA
);

CREATE TABLE CONTROLCINE.SESSAO(
	ID SERIAL PRIMARY KEY,
	HORARIO TIME NOT NULL,
	DATA DATE NOT NULL,
	ASSENTOSDIPONIVEIS INT NOT NULL,
	ESPECIAL BOOLEAN NOT NULL,
	PRECOINGRESSO FLOAT NOT NULL,
	IDFILME INT,
	CONSTRAINT FK_SESSAOFILME FOREIGN KEY (IDFILME) REFERENCES CONTROLCINE.FILME(ID)
);

CREATE TABLE CONTROLCINE.INGRESSO(
	ID SERIAL PRIMARY KEY,
	MEIA BOOLEAN NOT NULL
);

CREATE TABLE CONTROLCINE.CONTROLE_INGRESSO_SALA_SESSAO(
	IDSALA INT NOT NULL,
	IDSESSAO INT NOT NULL,
	IDINGRESSO INT NOT NULL,
	PRIMARY KEY(IDSALA,IDSESSAO,IDINGRESSO),
	CONSTRAINT fk_sala_controle FOREIGN KEY (IDSALA) REFERENCES CONTROLCINE.SALA(ID),
	CONSTRAINT fk_sessao_controle FOREIGN KEY (IDSESSAO) REFERENCES CONTROLCINE.SESSAO(ID),
	CONSTRAINT fk_ingresso_controle FOREIGN KEY (IDINGRESSO) REFERENCES CONTROLCINE.INGRESSO(ID)
);

CREATE TABLE CONTROLCINE.CLIENTE(
	ID INT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL
);

CREATE TABLE CONTROLCINE.FUNCIONARIO(
	ID CHAR(11) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	ADMIN BOOLEAN NOT NULL,
	SENHA VARCHAR(16) NOT NULL
);

CREATE TABLE CONTROLCINE.COMPRA(
	IDCLIENTE INT,
	IDFUNCIONARIO CHAR(11),
	IDINGRESSO INT,
	PRIMARY KEY(IDCLIENTE,IDFUNCIONARIO,IDINGRESSO),
	CONSTRAINT fk_cliente_compra FOREIGN KEY (IDCLIENTE) REFERENCES CONTROLCINE.CLIENTE(ID),
	CONSTRAINT fk_func_compra FOREIGN KEY (IDFUNCIONARIO) REFERENCES CONTROLCINE.FUNCIONARIO(ID),
	CONSTRAINT fk_ingresso_compra FOREIGN KEY (IDINGRESSO) REFERENCES CONTROLCINE.INGRESSO(ID)
);